#!/usr/bin/python3
import os
import sys

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('Gdk', '3.0')
gi.require_version('WebKit2', '4.0')
from gi.repository import Gtk

from lib import App

platform = 'youtube' if len(sys.argv) > 2 and sys.argv[2] == 'yt' else 'twitch'
if __name__ == "__main__":
  try:
    main = App(sys.argv[1], cookie_storage='{}/.config/stream_client'.format(os.environ['HOME']), quality="best", platform=platform)
    Gtk.main()
  except KeyboardInterrupt:
        print('Interrupted', file=sys.stderr)
  finally:
    main.release()
